# -*- coding: utf-8 -*-
"""Check point number°2 : Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OylBU5eSvu5gF_J00bNcqVb5WHN5wPV
"""

#ex1

for i in range(2000 , 3201):
    if ( (i/7 % 1) == 0  and (i/5 % 1) != 0) :
        print(i)

#ex2

a = int(input(print('Give us a number')))
fac=1
for i in range(a):
  fac=fac*(i+1)

print( "le factorielle de" , a , "est :" , fac)

import numpy as np

a = int(input(print('Give us a number')))

x2=[]

for i in range(1 , a):
  x=i*i
  x2.append(x)

print(x2)


res = {idx + 1 : x2[idx] for idx in range(len(x2))} 

print(res)

#ex4



word = str(input(print('Give us a word')))

index= int(input(print('Give us the index of the letter you wish to never see again ')))

word = word.replace(word[index-1], '', 1) 

print( "here is your new word : " ,  word)

#ex5 

#let's download some arrays from a csv file.

from array import *
import numpy as np



n=int(input('Give me the number of rows in your array'))

m=int(input('Give me the number of columns in your array'))

array=np.zeros((n,m))


for i in range(n):
  for j in range(m):
    array[i][j]= int((input(print('Give us a number'))))
    
    
  
arr=list(array)


for i in range(n):
  arr[i]=list(arr[i])



print ('Original array elements:' ,  array ) 

print ('Array to list: ' , arr)

#ex6

# Python code to demonstrate the 
# use of numpy.cov 
import numpy as np 

x = [0, 1, 2] 

y = [2 , 1 , 0] 

# find out covariance with respect columns 
cov_mat = np.stack((x, y), axis = 0) 

print(np.cov(cov_mat))

#ex7
 
import pandas as pd 
 
#Let's start by importing our csv file.

#here is the link to my csv file https://drive.google.com/drive/u/1/my-drive
 
df= pd.read_csv('/content/D_values - Sheet1 (4).csv')
 
#let's turn our D values into a list of values.
 
D=list(df['VAR'])
 
 
 
C=50
H=30
Q=[]
m=0
 
for i in D:
 
  y = round((2 * C * i)**(1/2)/H**(1/2))
  m=m+1
 
  print('Q',m, '= The square root of', '[(2 * C *',i,')/H]', '=' , y)